---

mysql_bind_address: 0.0.0.0

mysql_databases:
  - name: zabbix
    encoding: utf8
    collation: utf8_bin

mysql_users:
  - name: zabbix
    password: zabbix
    priv: "zabbix.*:ALL"
    host: "%"
